### ISSUE TITLE
Gitter channel?

### ISSUE THREAD

**Issue by solnic** [microrb/microrb.com#75]
Shall we open a gitter channel? It's been a huge success for ROM, just sayin :)

**Comment by krisleech** [comment]
+1

**Comment by solnic** [comment]
...please remember gitter has an irc bridge too, so everybody wins

**Comment by CrowdHailer** [comment]
Did this happen? I think I am in quite a few gitter channels and that is distracting but there is quite a high value to discussion on this project

**Comment by solnic** [comment]
I just created it: https://gitter.im/microrb/microrb.com

:tada:
